"use client"

import React, { useState, useEffect, useRef } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Sparkles, RefreshCw, Calendar, Clock, AlertTriangle, CheckCircle } from "lucide-react"
import { generateMorningBriefing } from "@/app/actions/morning-briefing"
import { format } from "date-fns"
import { useToast } from "@/hooks/use-toast"
import { Skeleton } from "@/components/ui/skeleton"
import { MOCK_USER_ID } from "@/lib/mock-user"

interface BriefingData {
  date: string
  briefing_text: string
  stats: {
    active_cases: number
    sol_warnings: number
    tasks_due_today: number
    overdue_tasks: number
  }
  generated_at: string
}

export function MorningBriefingCard() {
  const { toast } = useToast();
  const [generating, setGenerating] = useState(false);
  const [briefing, setBriefing] = useState<BriefingData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const hasAutoGenerated = useRef(false);

  const today = format(new Date(), 'yyyy-MM-dd');

  useEffect(() => {
    if (!hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleRefresh();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleRefresh = async () => {
    setGenerating(true);
    setIsLoading(true);
    try {
      const result = await generateMorningBriefing(MOCK_USER_ID, today);
      setBriefing(result as BriefingData);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      toast({
        variant: "destructive",
        title: "Briefing Error",
        description: message,
      });
    } finally {
      setGenerating(false);
      setIsLoading(false);
    }
  };

  const renderBriefingText = (text: string) => {
    return text.split('\n').filter(p => p.trim()).map((p, i) => (
      <p key={i} className={`text-sm leading-relaxed text-blue-50 ${i > 0 ? "mt-3" : ""}`}>
        {p}
      </p>
    ));
  };

  return (
    <Card className="border-none shadow-xl bg-gradient-to-br from-primary via-primary to-primary/90 text-white overflow-hidden relative group">
      <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none group-hover:scale-110 transition-transform duration-700">
        <Sparkles className="h-32 w-32" />
      </div>

      <CardHeader className="pb-4 relative z-10">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-accent rounded-xl shadow-lg ring-1 ring-white/20">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <div>
              <CardTitle className="text-xl font-black font-headline">Morning Intelligence</CardTitle>
              <CardDescription className="text-primary-foreground/60 font-bold uppercase tracking-widest text-[10px] flex items-center gap-1.5 mt-0.5">
                <Calendar className="h-3 w-3" /> {format(new Date(), 'EEEE, MMMM do')}
              </CardDescription>
            </div>
          </div>
          <Button
            variant="ghost"
            size="icon"
            onClick={handleRefresh}
            disabled={generating}
            className="text-white hover:bg-white/10 rounded-full h-10 w-10 transition-all hover:rotate-180"
          >
            <RefreshCw className={`h-4 w-4 ${generating ? 'animate-spin' : ''}`} />
          </Button>
        </div>
      </CardHeader>

      <CardContent className="space-y-6 relative z-10">
        <div className="bg-white/10 rounded-2xl p-5 backdrop-blur-md border border-white/10 shadow-inner min-h-[120px] flex flex-col justify-center">
          {isLoading || generating ? (
            <div className="space-y-3 py-2">
              <Skeleton className="h-4 w-full bg-white/10" />
              <Skeleton className="h-4 w-5/6 bg-white/10" />
              <Skeleton className="h-4 w-4/5 bg-white/10" />
            </div>
          ) : briefing?.briefing_text ? (
            renderBriefingText(briefing.briefing_text)
          ) : (
            <p className="text-sm text-blue-100 italic opacity-60">Click refresh to generate today's intelligence briefing.</p>
          )}
        </div>

        <div className="grid grid-cols-2 gap-3">
          {[
            { label: 'Active Cases', val: briefing?.stats?.active_cases ?? '—', icon: Clock, color: 'text-blue-400' },
            { label: 'SOL Warnings', val: briefing?.stats?.sol_warnings ?? '—', icon: AlertTriangle, color: 'text-red-400' },
            { label: 'Due Today', val: briefing?.stats?.tasks_due_today ?? '—', icon: CheckCircle, color: 'text-green-400' },
            { label: 'Overdue', val: briefing?.stats?.overdue_tasks ?? '—', icon: AlertTriangle, color: 'text-orange-400' },
          ].map((s, i) => (
            <div key={i} className="bg-white/5 rounded-xl p-3 border border-white/5 text-center group hover:bg-white/10 transition-colors">
              <div className="flex items-center justify-center mb-1">
                <s.icon className={`h-3 w-3 opacity-60 mr-1.5 ${s.color}`} />
                <span className="text-[9px] font-black uppercase tracking-wider text-white/60">{s.label}</span>
              </div>
              <div className="text-xl font-black">{s.val}</div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  )
}
